[project]
name = "pg-sql-helper"
version = "0.1.0"
description = "Postgresql helper to process returned columns from a given table"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "connectorx>=0.4.3",
]
